services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "5432:5432" # テスト用のポート
    networks:
      - narou_novel_app_db
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    volumes:
      - ./application:/application
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: sh -c "/usr/local/bin/entrypoint.sh"
    ports:
      - "4200:4200" # prefect用のポート
    networks:
      - narou_novel_app_db
volumes:
  db_data:
networks:
  narou_novel_app_db:
