"""empty message

Revision ID: 0256406775ca
Revises: 14974ab6057b
Create Date: 2025-01-01 06:23:35.638552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0256406775ca"
down_revision: Union[str, None] = "14974ab6057b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 外部キー制約を一時的に削除
    op.drop_constraint(
        "novel_keywords_keyword_id_fkey", "novel_keywords", type_="foreignkey"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "keyword",
        "keyword_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=43),
        existing_comment="キーワードのID",
        existing_nullable=False,
    )
    op.alter_column(
        "novel_keywords",
        "keyword_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=43),
        existing_comment="キーワードのID",
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # 外部キー制約を復旧
    op.create_foreign_key(
        "novel_keywords_keyword_id_fkey",
        "novel_keywords",
        "keyword",
        ["keyword_id"],
        ["keyword_id"],
    )


def downgrade() -> None:
    # 外部キー制約を一時的に削除
    op.drop_constraint(
        "novel_keywords_keyword_id_fkey", "novel_keywords", type_="foreignkey"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "novel_keywords",
        "keyword_id",
        existing_type=sa.String(length=43),
        type_=sa.UUID(),
        existing_comment="キーワードのID",
        existing_nullable=False,
    )
    op.alter_column(
        "keyword",
        "keyword_id",
        existing_type=sa.String(length=43),
        type_=sa.UUID(),
        existing_comment="キーワードのID",
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # 外部キー制約を復旧
    op.create_foreign_key(
        "novel_keywords_keyword_id_fkey",
        "novel_keywords",
        "keyword",
        ["keyword_id"],
        ["keyword_id"],
    )
