"""id列のデータ型を変更 (VARCHAR(26) → String(36))

Revision ID: 08f7d1c486c3
Revises: 93ac550ce511
Create Date: 2024-12-09 16:46:50.878172

このマイグレーションでは、ncode_mappingテーブルとrankテーブルのid列のデータ型を
VARCHAR(26)からString(36)に変更します。
"""


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08f7d1c486c3"
down_revision: Union[str, None] = "93ac550ce511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ncode_mapping",
        "id",
        existing_type=sa.VARCHAR(length=26),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "rank",
        "id",
        existing_type=sa.VARCHAR(length=26),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rank",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=26),
        existing_nullable=False,
    )
    op.alter_column(
        "ncode_mapping",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=26),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
