"""novel_keywordsテーブルの追加

Revision ID: 4b91e6c70ca7
Revises: ce4433ed9766
Create Date: 2024-12-17 05:46:29.424878

このマイグレーションでは、'novel_keywords'テーブルを追加します。
このテーブルは'ncode_mapping'テーブルと'keyword'テーブルに対する外部キー制約を持ちます。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b91e6c70ca7"
down_revision: Union[str, None] = "ce4433ed9766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novel_keywords",
        sa.Column("id", sa.UUID(), nullable=False, comment="ID"),
        sa.Column(
            "keyword_id", sa.UUID(), nullable=False, comment="キーワードのID"
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["ncode_mapping.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.keyword_id"],
        ),
        sa.PrimaryKeyConstraint("id", "keyword_id", name="pk_novel_keywords"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("novel_keywords")
    # ### end Alembic commands ###
