"""empty message

Revision ID: 8f38374865e2
Revises: 0262e81bf4ca
Create Date: 2024-12-17 01:16:19.875337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f38374865e2"
down_revision: Union[str, None] = "0262e81bf4ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keyword",
        sa.Column(
            "keyword_id", sa.UUID(), nullable=False, comment="キーワードのID"
        ),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="キーワード名",
        ),
        sa.PrimaryKeyConstraint("keyword_id"),
    )

    # 外部キーの削除
    op.drop_constraint("rank_id_fkey", "rank", type_="foreignkey")
    # 設定の変更
    op.execute(
        """
        ALTER TABLE ncode_mapping
        ALTER COLUMN id TYPE UUID USING id::uuid
        """
    )
    op.execute(
        """
        ALTER TABLE rank
        ALTER COLUMN id TYPE UUID USING id::uuid
        """
    )
    # 外部キーの設定
    op.create_foreign_key(
        "rank_id_fkey", "rank", "ncode_mapping", ["id"], ["id"]
    )


def downgrade() -> None:
    # 外部キーの削除
    op.drop_constraint("rank_id_fkey", "rank", type_="foreignkey")
    op.execute(
        """
        ALTER TABLE rank
        ALTER COLUMN id TYPE VARCHAR(36)
        """
    )
    op.execute(
        """
        ALTER TABLE ncode_mapping
        ALTER COLUMN id TYPE VARCHAR(36)
        """
    )

    # 外部キーを元に戻す
    op.create_foreign_key(
        "rank_id_fkey", "rank", "ncode_mapping", ["id"], ["id"]
    )

    # keywordテーブルの削除
    op.drop_table("keyword")
