"""empty message

Revision ID: 93ac550ce511
Revises: 
Create Date: 2024-12-06 17:16:31.130725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ac550ce511'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncode_mapping',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('ncode', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncode'),
    sa.UniqueConstraint('ncode', name='uq_ncode')
    )
    op.create_table('rank',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ncode_mapping.id'], ),
    sa.PrimaryKeyConstraint('id', 'rank', 'rank_date', name='pk_rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank')
    op.drop_table('ncode_mapping')
    # ### end Alembic commands ###
