"""authorテーブルのuseridに一意制約を追加

Revision ID: 9fc1dd8c5dd9
Revises: 498a9eaf15d1
Create Date: 2024-12-17 16:26:25.635258

このマイグレーションでは、authorテーブルのuseridカラムに一意制約を追加します。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fc1dd8c5dd9"
down_revision: Union[str, None] = "498a9eaf15d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "author", ["userid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "author", type_="unique")
    # ### end Alembic commands ###
