"""empty message

Revision ID: aa20b703db0d
Revises: 0256406775ca
Create Date: 2025-01-01 07:58:37.399623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa20b703db0d"
down_revision: Union[str, None] = "0256406775ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "author",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "author",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "author", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "biggenre",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "biggenre",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "biggenre", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "biggenre_genre",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "biggenre_genre",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "biggenre_genre", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "genre",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "genre",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "genre", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "keyword",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "keyword",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "keyword", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "novel",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "novel_keywords",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel_keywords",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel_keywords", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "novel_type",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel_type",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "novel_type", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "rank_type",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "rank_type",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "rank_type", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rank_type", "deleted_at")
    op.drop_column("rank_type", "updated_at")
    op.drop_column("rank_type", "created_at")
    op.drop_column("novel_type", "deleted_at")
    op.drop_column("novel_type", "updated_at")
    op.drop_column("novel_type", "created_at")
    op.drop_column("novel_keywords", "deleted_at")
    op.drop_column("novel_keywords", "updated_at")
    op.drop_column("novel_keywords", "created_at")
    op.drop_column("novel", "deleted_at")
    op.drop_column("novel", "updated_at")
    op.drop_column("novel", "created_at")
    op.drop_column("keyword", "deleted_at")
    op.drop_column("keyword", "updated_at")
    op.drop_column("keyword", "created_at")
    op.drop_column("genre", "deleted_at")
    op.drop_column("genre", "updated_at")
    op.drop_column("genre", "created_at")
    op.drop_column("biggenre_genre", "deleted_at")
    op.drop_column("biggenre_genre", "updated_at")
    op.drop_column("biggenre_genre", "created_at")
    op.drop_column("biggenre", "deleted_at")
    op.drop_column("biggenre", "updated_at")
    op.drop_column("biggenre", "created_at")
    op.drop_column("author", "deleted_at")
    op.drop_column("author", "updated_at")
    op.drop_column("author", "created_at")
    # ### end Alembic commands ###
