"""empty message

Revision ID: cfcb3ff9d4c9
Revises: 8f38374865e2
Create Date: 2024-12-17 05:30:21.491769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfcb3ff9d4c9"
down_revision: Union[str, None] = "8f38374865e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("author_id", sa.UUID(), nullable=False, comment="作者のID"),
        sa.Column(
            "userid",
            sa.Integer(),
            nullable=False,
            comment="作者のユーザーID(数値)",
        ),
        sa.Column(
            "writer", sa.String(length=128), nullable=False, comment="作者名"
        ),
        sa.PrimaryKeyConstraint("author_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("author")
    # ### end Alembic commands ###
