"""empty message

Revision ID: d6310ca487fc
Revises: 9fc1dd8c5dd9
Create Date: 2024-12-17 16:42:46.085925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6310ca487fc"
down_revision: Union[str, None] = "9fc1dd8c5dd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "novel_type", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "novel_type", type_="unique")
    # ### end Alembic commands ###
