"""empty message

Revision ID: d6c12aa8111c
Revises: 07fdab18fd41
Create Date: 2024-12-16 15:03:59.563284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6c12aa8111c"
down_revision: Union[str, None] = "07fdab18fd41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novel_type",
        sa.Column(
            "code", sa.Integer(), nullable=False, comment="ノベルの形式のコード"
        ),
        sa.Column(
            "name",
            sa.String(length=2),
            nullable=False,
            comment="ノベルの形式名",
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("novel_type")
    # ### end Alembic commands ###
