"""biggenre_genreの追加

Revision ID: ec45656b488a
Revises: d6310ca487fc
Create Date: 2024-12-22 11:24:22.760623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec45656b488a"
down_revision: Union[str, None] = "d6310ca487fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biggenre_genre",
        sa.Column("biggenre_code", sa.Integer(), nullable=False),
        sa.Column("genre_code", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["biggenre_code"],
            ["biggenre.code"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_code"],
            ["genre.code"],
        ),
        sa.PrimaryKeyConstraint(
            "biggenre_code", "genre_code", name="pk_biggenre_code_genre_code"
        ),
    )
    op.drop_constraint("genre_biggenre_code_fkey", "genre", type_="foreignkey")
    op.drop_column("genre", "biggenre_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "genre",
        sa.Column(
            "biggenre_code",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="大ジャンルのコード",
        ),
    )
    op.create_foreign_key(
        "genre_biggenre_code_fkey",
        "genre",
        "biggenre",
        ["biggenre_code"],
        ["code"],
    )
    op.drop_table("biggenre_genre")
    # ### end Alembic commands ###
